### ISSUE TITLE
yamlに設定書く

### ISSUE THREAD

**Issue by shosatojp** [shosatojp/ipban#2]
```yaml
targets:
  - path: /var/log/mail.log
    regex: ".*\[(\d+\.\d+\.\d+\.\d+)\]: SASL LOGIN authentication failed.*"
```
